language: java
dist: trusty
jdk:
  oraclejdk8

before_install:
  - chmod +x mvnw
  - pip install --user codecov

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script:  mvn jacoco:prepare-agent test jacoco:report
      after_success: codecov

services:
  - postgresql

before_script:
  - psql -c 'create database demo;' -U postgres