package com.example.demo.enums;

public enum PositionType {
    KEEPER,
    CENTRE_BACK, SWEEPER, FULL_BACK, WING_BACK,
    CENTRE_MIDFIELD, DEFENSIVE_MIDFIELD, ATTACKING_MIDFIELD, WIDE_MIDFIELD,
    CENTRE_FORWARD, SECOND_STRIKER, WINGER;
}
