spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.maxActive: 10
spring.datasource.maxIdle: 5
spring.datasource.minIdle: 2
spring.datasource.initialSize: 5
spring.datasource.removeAbandoned: true



server:
   port: 8090 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data